---
output:
  html_document: default
  pdf_document: default
  word_document: default
---


```{r include=FALSE}
#load relevant libraries
#load packages

rm(list=ls())

if(!require(installr)) {
  install.packages("installr"); 
  require(installr)
} #load

#updateR()


if(!require("pacman")) install.packages('pacman')
pacman::p_load(NetworkToolbox,
               # graph,
               leidenAlg,
               ggthemes,
               knitr ,
               data.table,
               igraph,
               qgraph,
               tidyverse,
               dplyr,
               ggplot2,
               naniar,
               gdata,
               doParallel,
               wCorr,
               qgraph,
               MASS,
               Matrix,
               matrixcalc,
               randcorr,
               rWishart,
               devtools,
               ggpubr,
               tinytex,
               ggdark )

```

##set working directory

```{r include=FALSE}

### MANUAL INPUT: specify and set working directory ###
workdirec <-"C:/Users/20225262/OneDrive - TU Eindhoven/Documents/GitHub/Testing-Modules-of-Social-Tipping" 


setwd(workdirec)
source("functions_behaviorspace_table_output_handling.R")

### MANUAL INPUT: Optionally specify filepath (i.e. where the behaviorspace csv is situated) ###
#NOTE: if csv files are placed in the workdirec, then leave filesPath unchanged
filesPath <- ""
### MANUAL INPUT: specify filenames ###
filesNames <- c("C:/Users/20225262/OneDrive - TU Eindhoven/Documents/Models/Social Tipping Modules/Network_Metrics-1700765.csv")


```


##Read data and rename columns
```{r include=FALSE}
# READ DATA ---------------------------------------------------------------

df <- loadData(filesPath, filesNames)


# REMOVE IRRELEVANT VARIABLES ---------------------------------------------------------------

df <- removeVariables(df)

# RENAME VARIABLES ---------------------------------------------------------------
printColumnNames(df)

  ### MANUAL INPUT: specify new (easy-to-work-with) variable names ###
  new_variable_names <- list(
    "Run_Number",
    "Dekkers_Power",
   "Node_Degree",
  #   "Tipping_Strategy",
      "Communities",
     "RP",
  #  "duration_to_decision",
 #    "Population_Size",
      "CC",
  #    "Innovators",
  # "Threshold_Pop",
  #    "ticks",
    "Mean_SCC",
    "Mean_EC",
    "Mean_BC",
    "Mean_CCC",
 "Mean_CLUS",
  "MWPL",
  #"MOD",
    "MPL",
     "Var_CC",
    "Var_EC",
    "Var_BC",
    "Var_CCC",
 "Var_CLUS",
       "Majority_Green",
   "Green_Percentage"
  #     "Sim_Time"
 
    )

#change variable names
variable_names <- names(df)
if (length(variable_names) == length(new_variable_names)) {
  clean_df <- changeColumnNames(df, new_variable_names)
} else {
  print (length(variable_names))
  print (length(new_variable_names))
  print("ERROR: the number of variable names you specified is not the same as the number of variables present within the dataframe; please check again")
}



```






##Transform variables with right label
```{r include=FALSE}
#transform 'measurement' variable to numeric (as to avoid ggplot errors)
#clean_df$NCSAG <- as.numeric(clean_df$NCSAG)
#clean_df$NCSAB <- as.numeric(clean_df$NCSAB)
#clean_df$Sim_Time <- as.numeric(clean_df$Sim_Time)
#clean_df$Green_Percentage <- as.numeric(clean_df$Green_Percentage)
#clean_df$Threshold_Pop <- as.factor(clean_df$Threshold_Pop)

clean_df$Node_Degree <- as.factor(clean_df$Node_Degree)
#clean_df$Mean_Cluster_Coefficient <- as.factor(clean_df$Mean_Cluster_Coefficient)
#clean_df$Majority_Green <- as.numeric(clean_df$Majority_Green)
clean_df$Dekkers_Power <- as.factor(clean_df$Dekkers_Power)
#clean_df$duration_to_decision <- as.factor(clean_df$duration_to_decision)
clean_df$RP<- as.factor(clean_df$RP)
#clean_df$Stop_Time <- as.factor(clean_df$Stop_Time)
#clean_df$Population_Size <- as.factor(clean_df$Population_Size)
#clean_df$Innovators <- as.factor(clean_df$Innovators)
#clean_df$Tipping_Strategy<- as.factor(clean_df$Tipping_Strategy)
clean_df$Communities<- as.factor(clean_df$Communities)
clean_df$CC<- as.factor(clean_df$CC)
#clean_df$MPL <- as.numeric(clean_df$MPL)
#clean_df$MWPL <- as.numeric(clean_df$MWPL)

clean_df <- mutate(clean_df, MPL_Ratio = MWPL / MPL )


```

```{r include=false}

#df_long <- dplyr::select(clean_df)
df_long <- gather(clean_df, variable, measurement, Mean_SCC:Green_Percentage)

# SPECIFY VARIABLE MEASUREMENT SCALES -----------------------------------------------------
### MANUAL INPUT: in order for ggplot and plotly to work, one must specify the following: ###
#-> continuous decimal (floating) variables as 'numeric'
#-> continuous integer variables as 'integer'
#-> discrete (or categorical) variables as 'factor'

#print an overview of variables and their measurement scales
str(df_long)
#transform 'measurement' variable to numeric (as to avoid ggplot errors)
df_long$measurement <- as.numeric(df_long$measurement)
#round 'measurement' variable to 4 decimals
df_long$measurement <- round(df_long$measurement, 4)
#convert categorical variables to factors (as to avoid ggplot errors)
df_long$Run_Number <- as.integer(df_long$Run_Number)
df_long$variable <- as.factor(df_long$variable)



```


##Make Graphs
--------------------------------- Mean Path Length
```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}
#df_mean$Threshold_Pop <- as.factor(df_mean$Threshold_Pop)
# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
clean_df %>% filter(Node_Degree == 10) %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = Mean_CLUS, y = MPL_Ratio, shape= Communities, size=Dekkers_Power, color=CC)) +
    geom_point()+
    xlab("Mean_Path_Length") +
    ylab("Mean_Clustering_Coefficient") + 
   labs(title = "Mean Path Length for network metrics")+
    scale_color_viridis_d()+
 # scale_y_log10()+
#scale_x_log10()+
    theme_bw()+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid( RP ~ Node_Degree, labeller = label_both ) 



```
```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}
#df_mean$Threshold_Pop <- as.factor(df_mean$Threshold_Pop)
# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
df_long %>% filter(variable == "MPL_Ratio") %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = measurement, y = Rewiring_Proportion, size=Communities, color=Clustering_Coefficient)) +
    geom_point(size=2)+
    xlab("Mean_Complex_Path_Length") +
    ylab("Rewiring_Proportion") + 
   labs(title = "Mean Complex Path Length for network metrics")+
    scale_color_viridis_d()+
  scale_x_log10()+
    theme_bw()+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid( Dekkers_Power ~ Node_Degree, labeller = label_both ) 



```

```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}
#df_mean$Threshold_Pop <- as.factor(df_mean$Threshold_Pop)
# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
df_long %>% filter(variable == "Mean_SCC") %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = measurement, y = Rewiring_Proportion, size = Communities, color=Clustering_Coefficient)) +
    geom_point(shape = 21 )+
    xlab("Mean_Closeness_Centrality") +
    ylab("Rewiring_Proportion") + 
   labs(title = "Mean Closeness Centrality for network metrics")+
    scale_color_viridis_d()+
  scale_x_log10()+
    theme_bw()+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid( Dekkers_Power ~ Node_Degree, labeller = label_both ) 



```
```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}
#df_mean$Threshold_Pop <- as.factor(df_mean$Threshold_Pop)
# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
df_long %>% filter(variable == "Mean_CCC") %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = measurement, y = Rewiring_Proportion, shape = Communities, color=Clustering_Coefficient)) +
    geom_point(size=2)+
    xlab("Mean Complex Closeness Centrality") +
    ylab("Rewiring_Proportion") + 
   labs(title = "Mean Complex Closeness Centrality for network metrics")+
    scale_color_viridis_d()+
  scale_x_log10()+
    theme_bw()+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid( Dekkers_Power ~ Node_Degree, labeller = label_both ) 



```

------------------------ Mean Clustering Coefficient
```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}

# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
clean_df %>% filter() %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = Mean_CC, y = Green_Percentage, color=Tipping_Strategy)) +
    geom_point(size=2)+
    xlab("Mean-Clustering-Coefficient") +
    ylab("Green_Percentage") + 
   labs(title = "Percentage Majroity Green for Mean_Clustering_Coefficient",
       subtitle = "Rewiring_Proportion == 0.05/0.25//0.45, Dekkers_Power == 1/3/5/7, Pop_size == 420, Decision_Module == Threshold, Rep_Runs == 50")+
    scale_color_viridis_d()+
    theme_bw()+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid( Threshold_Pop ~ Innovators, labeller = label_both ) 



```
```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}

# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
clean_df %>% filter() %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = Mean_CC, y = Sim_Time, color=Tipping_Strategy)) +
    geom_point(size=2)+
    xlab("Mean-Clustering-Coefficient") +
    ylab("Simulation_Time ") + 
   labs(title = "Percentage Simulation_Time for Mean_Clustering_Coefficient",
       subtitle = "Rewiring_Proportion == 0.05/0.25//0.45, Dekkers_Power == 1/3/5/7, Pop_size == 420, Decision_Module == Threshold, Rep_Runs == 50")+
    scale_color_viridis_d()+
    theme_bw()+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid( Threshold_Pop ~ Innovators, labeller = label_both ) 

```



Sensitivity to Dekkers_Power and Rewiring_Proportion
```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}

# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
clean_df  %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = Innovators, y=Majority_Green, shape=duration_to_decision, fill=Tipping_Strategy, color=Tipping_Strategy)) +
    geom_point(size=3) +
    xlab("Social Innovators") +
    ylab("Majority Green") + 
    labs(title = "Mean Majority Green across 75 repetitive runs")+
 scale_shape_binned()+
   scale_color_manual(values=c('red', 'darkgreen','blue'))+
    theme_bw()+
 # xlim(0, 11000)+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid(Rewiring_Proportion~Dekkers_Power, labeller = label_both ) 



```

```{r echo=FALSE, fig.height=15, fig.width=15, message=FALSE, warning=FALSE, results='asis'}
clean_df$Innovators <- as.factor(clean_df$Innovators)
# "Mean_Average_Path", #Connections","Mean_Node_Degree", "Mean_Cluster_Coefficient"
clean_df %>% filter(duration_to_decision ==  1)  %>%
   dplyr::sample_frac(1) %>%
ggplot(aes(x = Innovators, y=Sim_Time, fill=Tipping_Strategy)) +
    #geom_point(aes(color=Majority_Green)) +
#  geom_point(data = df_mean,aes(x = Innovators, y=Majority_Green, shape=Tipping_Strategy, color=Tipping_Strategy)) +
    geom_boxplot() +
    xlab("Social Innovators") +
    ylab("Sim_Time") + 
    labs(title = "Sim time distribution across 75 repetitive runs")+
   scale_color_viridis_d()+
  scale_y_log10()+ #sec.axis = sec_axis(~.*1/log(.), name="Second Axis"))+
    theme_bw()+
 # xlim(0, 11000)+
    theme(strip.background = element_rect(fill="black"),
          strip.text = element_text(size=12, colour="white", face = "bold"), 
          plot.title = element_text( size = 18), 
          plot.subtitle = element_text( size = 15),
          axis.title = element_text( size = 18) ) +
   facet_grid(Rewiring_Proportion~Dekkers_Power, labeller = label_both ) 



```

